"""baseline schema

Revision ID: 26d9c10ac00a
Revises:
Create Date: 2026-03-06 16:18:53.636486

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26d9c10ac00a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=False),
        sa.Column("verified_count", sa.Integer(), nullable=False),
        sa.Column("not_found_count", sa.Integer(), nullable=False),
        sa.Column("ambiguous_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("unverified_no_token_count", sa.Integer(), nullable=False),
        sa.Column("input_text_excerpt", sa.Text(), nullable=True),
        sa.Column("warning_text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "telemetry_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("install_id", sa.String(length=64), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("verified_count", sa.Integer(), nullable=True),
        sa.Column("not_found_count", sa.Integer(), nullable=True),
        sa.Column("ambiguous_count", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=True),
        sa.Column("unverified_no_token_count", sa.Integer(), nullable=True),
        sa.Column("had_warning", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "citation_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_run_id", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("citation_type", sa.String(length=128), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("resolved_from", sa.Text(), nullable=True),
        sa.Column("verification_status", sa.String(length=64), nullable=True),
        sa.Column("verification_detail", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["audit_run_id"], ["audit_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("citation_results")
    op.drop_table("telemetry_events")
    op.drop_table("audit_runs")
    # ### end Alembic commands ###
