"""add statute_count to audit_runs and telemetry_events

Revision ID: a6175d945c95
Revises: 692bad634655
Create Date: 2026-03-06 21:07:42.027117

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6175d945c95"
down_revision: Union[str, Sequence[str], None] = "692bad634655"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("statute_count", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("statute_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.drop_column("statute_count")

    with op.batch_alter_table("audit_runs", schema=None) as batch_op:
        batch_op.drop_column("statute_count")

    # ### end Alembic commands ###
